### ISSUE TITLE
Colons apperaing in sidebar

### ISSUE THREAD

**Issue by IDontReallyHaveOne** [systemetric/docs.robocon.uk#4]
More subjective and can be ignored, but colons form the titles appear in the sidebar for navigation; personally I don't like how it looks

![image](https://github.com/user-attachments/assets/0027b868-8bd6-46aa-b0f2-16a5782b8bf0)

![image](https://github.com/user-attachments/assets/0bb3b353-9a09-4e6a-af39-6ae13dc3a484)

**Comment by what-does-that-do** [comment]
Ooh yes these are very pesky and annoying - will fix these soon!
